In [1]:
import numpy as np
import matplotlib.pyplot as plt

#### Koda za stolpec in vrstico

In [6]:
Vektor = np.array([1,2,3])
# vrstica
vrstica = Vektor[np.newaxis]

# stolpec
stolpec = Vektor[:, np.newaxis]
print(f'Vektor shape: {Vektor.shape}')
print(f'vrstica shape: {vrstica.shape}')
print(f'stolpec shape: {stolpec.shape}')

Vektor shape: (3,)
vrstica shape: (1, 3)
stolpec shape: (3, 1)


Transpose ne naredi nič, tudi če izbereš prvi stolpec

In [17]:
matrika = np.array([[1,2,3], [4,5,6]])
print(f'matrika shape: {matrika.shape}')
print(matrika[:, :])
print("----------")
print(matrika[:, 0], matrika[:, 0].shape)
print("----------")
print(matrika[:, 0].T, matrika[:, 0].T.shape)
print("----------")
print(matrika[:, [0]], matrika[:, [0]].shape)

matrika shape: (2, 3)
[[1 2 3]
 [4 5 6]]
----------
[1 4] (2,)
----------
[1 4] (2,)
----------
[[1]
 [4]] (2, 1)
