In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Mass-Spring-Damper System

In this example, we consider a simple mechanical system consisting of five masses connected in a line by springs and dampers. Such systems are commonly used to model vibrations in mechanical structures.

## Theory

### 1. System Description

A mass-spring-damper system can be represented using a set of masses (\($m_i$\)), springs with stiffness constants (\(k_i\)), and dampers with damping coefficients (\(c_i\)). 

### 2. Equations of Motion

The motion of each mass is governed by Newton's second law. For a system with \(n\) masses, the equations of motion can be written in matrix form as:

\[ M \ddot{x}(t) + C \dot{x}(t) + K x(t) = F(t) \]

where:
- \( M \) is the mass matrix.
- \( C \) is the damping matrix.
- \( K \) is the stiffness matrix.
- \( x(t) \) is the displacement vector of the masses.
- \( \dot{x}(t) \) and \( \ddot{x}(t) \) are the first and second time derivatives of \( x(t) \), representing velocity and acceleration respectively.
- \( F(t) \) is the external force vector (if any).

### 3. Mass Matrix (M)

The mass matrix \(M\) is typically a diagonal matrix if each mass is considered independent:

\[ M = \begin{pmatrix}
m_1 & 0 & 0 & 0 & 0 \\
0 & m_2 & 0 & 0 & 0 \\
0 & 0 & m_3 & 0 & 0 \\
0 & 0 & 0 & m_4 & 0 \\
0 & 0 & 0 & 0 & m_5 \\
\end{pmatrix} \]

### 4. Damping Matrix (C)

The damping matrix \(C\) accounts for the dampers between masses:

\[ C = \begin{pmatrix}
c_1 + c_2 & -c_2 & 0 & 0 & 0 \\
-c_2 & c_2 + c_3 & -c_3 & 0 & 0 \\
0 & -c_3 & c_3 + c_4 & -c_4 & 0 \\
0 & 0 & -c_4 & c_4 + c_5 & -c_5 \\
0 & 0 & 0 & -c_5 & c_5 \\
\end{pmatrix} \]

### 5. Stiffness Matrix (K)

The stiffness matrix \(K\) accounts for the springs between masses:

\[ K = \begin{pmatrix}
k_1 + k_2 & -k_2 & 0 & 0 & 0 \\
-k_2 & k_2 + k_3 & -k_3 & 0 & 0 \\
0 & -k_3 & k_3 + k_4 & -k_4 & 0 \\
0 & 0 & -k_4 & k_4 + k_5 & -k_5 \\
0 & 0 & 0 & -k_5 & k_5 \\
\end{pmatrix} \]

### 6. Solving the System

To solve the system, we typically use numerical methods such as the finite difference method or built-in solvers in Python libraries (e.g., `scipy.integrate.solve_ivp`).

In the following sections, we will set up the system in Python and solve the equations of motion using numerical methods.


In [2]:
# Import necessary libraries
import numpy as np

# Define the parameters for the masses, damping coefficients, and stiffness constants
masses = np.array([1.0, 1.0, 1.0, 1.0, 1.0])  # Example mass values for each of the 5 masses
damping_coeffs = np.array([0.5, 0.5, 0.5, 0.5, 0.5])  # Example damping coefficients for each damper
stiffness_coeffs = np.array([100.0, 100.0, 100.0, 100.0, 100.0])  # Example stiffness constants for each spring

# Number of masses
n = len(masses)

# Create the mass matrix (M)
M = np.diag(masses)

# Create the damping matrix (C)
C = np.zeros((n, n))
for i in range(n-1):
    C[i, i] += damping_coeffs[i] + damping_coeffs[i+1]
    C[i, i+1] = -damping_coeffs[i+1]
    C[i+1, i] = -damping_coeffs[i+1]
C[-1, -1] += damping_coeffs[-1]

# Create the stiffness matrix (K)
K = np.zeros((n, n))
for i in range(n-1):
    K[i, i] += stiffness_coeffs[i] + stiffness_coeffs[i+1]
    K[i, i+1] = -stiffness_coeffs[i+1]
    K[i+1, i] = -stiffness_coeffs[i+1]
K[-1, -1] += stiffness_coeffs[-1]

# Print the matrices for verification
print("Mass matrix (M):")
print(M)
print("\nDamping matrix (C):")
print(C)
print("\nStiffness matrix (K):")
print(K)


Mass matrix (M):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Damping matrix (C):
[[ 1.  -0.5  0.   0.   0. ]
 [-0.5  1.  -0.5  0.   0. ]
 [ 0.  -0.5  1.  -0.5  0. ]
 [ 0.   0.  -0.5  1.  -0.5]
 [ 0.   0.   0.  -0.5  0.5]]

Stiffness matrix (K):
[[ 200. -100.    0.    0.    0.]
 [-100.  200. -100.    0.    0.]
 [   0. -100.  200. -100.    0.]
 [   0.    0. -100.  200. -100.]
 [   0.    0.    0. -100.  100.]]


# Admittance of the System

Admittance is a concept from electrical engineering that can be extended to mechanical systems. It represents how easily a system responds to external forces and is the inverse of impedance. In mechanical systems, admittance is related to the system's transfer function, which describes the relationship between input force and output displacement.

## 1. Transfer Function

For a linear time-invariant (LTI) system, the transfer function $(H(s)$) is defined in the Laplace domain as the ratio of the Laplace transform of the output $(X(s)$) to the Laplace transform of the input $(F(s)$):

$[ H(s) = \frac{X(s)}{F(s)} $]

## 2. System Dynamics

Considering the equations of motion for our mass-spring-damper system:

$[ M \ddot{x}(t) + C \dot{x}(t) + K x(t) = F(t) $]

Taking the Laplace transform of both sides, assuming zero initial conditions, we get:

$[ M s^2 X(s) + C s X(s) + K X(s) = F(s) $]

Rearranging to solve for \(X(s)\):

$[ X(s) = \left( M s^2 + C s + K \right)^{-1} F(s) $]

## 3. Admittance Function

The admittance function $(Y(s)$) is the transfer function $(H(s)$) in mechanical systems:

$[ Y(s) = H(s) = \left( M s^2 + C s + K \right)^{-1} $]

This represents the frequency-dependent response of the system to an applied force. The admittance function provides insight into how the system will behave at different frequencies.
