In [34]:
import numpy as np
import matplotlib.pyplot as plt
import funkcije_seminar as f

In [2]:
t = f.neodvisna_spremenljivka_t(20)
print(t)

[0.0000e+00 1.0000e-03 2.0000e-03 ... 1.9998e+01 1.9999e+01 2.0000e+01]


In [3]:
f.sum(2,3)

5

In [14]:
#create empty matrix 3x3
A = np.zeros((3,3))
A[0,0] = 3;
A[0, 1] = -1;
A[0, 2] = 0;
A[1, 0] = -1/2;
A[1, 1] = 2;
A[1, 2] = -3/2;
A[2, 0] = 0;
A[2, 1] = -3/5;
A[2, 2] = 3/5;
M = np.zeros((3,3))
M[0,0] = 1
M[1,1] = 2
M[2,2] = 5
M

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 5.]])

In [20]:
# calculate eigenvalues and eigenvectors of matrix A
eigval, eigvec = np.linalg.eig(A)
print(eigvec)
eigvec[:,0] = eigvec[:,0]/eigvec[1,0]
eigvec[:,1] = eigvec[:,1]/eigvec[1,1]
eigvec[:,2] = eigvec[:,2]/eigvec[1,2]
eigvec


[[-0.91076631 -0.70648308  0.21820598]
 [ 0.40402635 -0.65539688  0.63627162]
 [-0.08524927  0.26708911  0.73996255]]


array([[-2.254225  ,  1.07794697,  0.3429447 ],
       [ 1.        ,  1.        ,  1.        ],
       [-0.21099929, -0.40752271,  1.16296645]])

In [33]:
eigvec
#column 3 of eigvec is eigvec2 column 1
eigvec2 =np.zeros((3,3))
X1 = eigvec2[:,0] = eigvec[:,2]
X2 = eigvec2[:,2] = eigvec[:,0]
X3 = eigvec2[:,1] = eigvec[:,1]
eigvec2

array([[ 0.3429447 ,  1.07794697, -2.254225  ],
       [ 1.        ,  1.        ,  1.        ],
       [ 1.16296645, -0.40752271, -0.21099929]])

In [24]:
M = np.zeros((3,3))
M[0,0] = 1
M[1,1] = 2
M[2,2] = 5
K = np.zeros((3,3))
K[0,0] = 3
K[0, 1] = -1
K[0, 2] = 0
K[1, 0] = -1
K[1,1] = 4
K[1, 2] = -3
K[2, 0] = 0
K[2, 1] = -3
K[2,2] = 3
M, K

(array([[1., 0., 0.],
        [0., 2., 0.],
        [0., 0., 5.]]),
 array([[ 3., -1.,  0.],
        [-1.,  4., -3.],
        [ 0., -3.,  3.]]))

In [25]:
M1 = X1 @ M @ X1
M2 = X2 @ M @ X2
M3 = X3 @ M @ X3
M1, M2, M3

(8.880065858219432, 7.304133875909408, 3.992343475747697)

In [26]:
K1 = X1 @ K @ X1
K2 = X2 @ K @ X2
K3 = X3 @ K @ X3
K1, K2, K3

(0.7466179908828808, 25.152598973534648, 8.273375628175057)

In [27]:
eigval

array([3.44361144, 2.07231058, 0.08407798])

In [32]:
modal_mass_matrix = np.zeros((3,3))
for i in range(3):
    modal_mass_matrix[i,i] = eigvec2[:,i].T @ M @ eigvec2[:,i]
print("Modal mass matrix: ")
print(modal_mass_matrix)

Modal mass matrix: 
[[8.88006586 0.         0.        ]
 [0.         3.99234348 0.        ]
 [0.         0.         7.30413388]]
